spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shirodemo?useUnicode=true&characterEncoding=utf8&useSSL=false
##  redis
  redis:
    port: 6379
    host: localhost
    database: 0
## mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wm.shirodemo.model

